baseURL = '/'
languageCode = 'en-us'
title = 'Rushi Panchariya'
# Google Analytics setup by enviroment variable
# HUGO_GOOGLEANALYTICS
# googleAnalytics = '' 

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 4
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  readingTime = true
  fullWidthTheme = false
  hideComments = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "RushiPanchariya"
  site = "RushiPanchariya"

[languages]
  [languages.en.params]
    languageName = "English"
    title = "RushiPanchariya"
    subtitle = "Personal Insights, Blogs, and Notes"
    owner = "Rushi"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Rushi Panchariya"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"

[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v3'